"""event table

Revision ID: 41d9b3de9247
Revises: ccd8a5f026a5
Create Date: 2023-05-05 13:47:03.167207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d9b3de9247'
down_revision = 'ccd8a5f026a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.String(length=140), nullable=True),
    sa.Column('eventadress', sa.String(length=140), nullable=True),
    sa.Column('eventdate', sa.String(length=140), nullable=True),
    sa.Column('eventtime', sa.String(length=140), nullable=True),
    sa.Column('eventhost', sa.String(length=140), nullable=True),
    sa.Column('eventcontact', sa.String(length=140), nullable=True),
    sa.Column('eventdetails', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eventsdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventsdb',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eventname', sa.VARCHAR(length=140), nullable=True),
    sa.Column('eventadress', sa.VARCHAR(length=140), nullable=True),
    sa.Column('eventdate', sa.VARCHAR(length=140), nullable=True),
    sa.Column('eventtime', sa.VARCHAR(length=140), nullable=True),
    sa.Column('eventhost', sa.VARCHAR(length=140), nullable=True),
    sa.Column('eventcontact', sa.VARCHAR(length=140), nullable=True),
    sa.Column('eventdetails', sa.VARCHAR(length=140), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    # ### end Alembic commands ###
