"""users table

Revision ID: a130b51bcba9
Revises: 569065428f06
Create Date: 2023-04-10 12:00:52.387300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a130b51bcba9'
down_revision = '569065428f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('email_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('phonenumber_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('city_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('jobtitle_me', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('jobtitle_me')
        batch_op.drop_column('city_me')
        batch_op.drop_column('phonenumber_me')
        batch_op.drop_column('email_me')
        batch_op.drop_column('fullname_me')

    # ### end Alembic commands ###
