"""users table

Revision ID: ccd8a5f026a5
Revises: a130b51bcba9
Create Date: 2023-05-04 11:10:52.406526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd8a5f026a5'
down_revision = 'a130b51bcba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventsdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.String(length=140), nullable=True),
    sa.Column('eventadress', sa.String(length=140), nullable=True),
    sa.Column('eventdate', sa.String(length=140), nullable=True),
    sa.Column('eventtime', sa.String(length=140), nullable=True),
    sa.Column('eventhost', sa.String(length=140), nullable=True),
    sa.Column('eventcontact', sa.String(length=140), nullable=True),
    sa.Column('eventdetails', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventsdb')
    # ### end Alembic commands ###
